name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  release:

    runs-on: ubuntu-latest

    environment: build
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master

      - name: Package and release
        uses: BigWigsMods/packager@master